export const cardData = [
  {
    id: 0,
    title: 'Lịch nghỉ lễ 30/4 - 1/5',
    description: 'Lịch nghỉ lễ 30/4 - 1/5 năm 2025',
    image: 'https://picsum.photos/400/300',
    time: '10:00 - 06/05/2025',
  },
  {
    id: 1,
    title: 'Lịch nghỉ lễ 2/9',
    description: 'Lịch nghỉ lễ 2/9 năm 2025. Thay đổi giờ làm việc',
    image: 'https://picsum.photos/400/300',
    time: '10:00 - 06/05/2025',
  },
  {
    id: 2,
    title: 'Nhân sự mới',
    description:
      'Chào đón nhân sự mới Khang dz no 1 siêu cấp vip pro nhìn là mê Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    image: 'https://picsum.photos/400/300',
    name: 'Bùi An Khang',
    time: '10:00 - 06/05/2025',
    avatar: 'https://picsum.photos/400/300',
  },
  {
    id: 3,
    title: 'Europe Street beat',
    description: 'www.instagram.com',
    image: 'https://picsum.photos/400/300',
    time: '10:00 - 06/05/2025',
  },
  {
    id: 4,
    title: 'Europe Street beat',
    description: 'www.instagram.com',
    image: 'https://picsum.photos/400/300',
    time: '10:00 - 06/05/2025',
  },
  {
    id: 5,
    title: 'Europe Street beat',
    description: 'www.instagram.com',
    image: 'https://picsum.photos/400/300',
    time: '10:00 - 06/05/2025',
  },
  {
    id: 6,
    title: 'Lịch nghỉ lễ 30/4 - 1/5',
    description: 'Lịch nghỉ lễ 30/4 - 1/5 năm 2025',
    image: 'https://picsum.photos/400/300',
    time: '10:00 - 06/05/2025',
  },
  {
    id: 7,
    title: 'Lịch nghỉ lễ 2/9',
    description: 'Lịch nghỉ lễ 2/9 năm 2025. Thay đổi giờ làm việc',
    image: 'https://picsum.photos/400/300',
    time: '10:00 - 06/05/2025',
  },
  {
    id: 8,
    title: 'Nhân sự mới',
    description: 'Chào đón nhân sự mới Nguyễn Văn A',
    image: 'https://picsum.photos/400/300',
    time: '10:00 - 06/05/2025',
  },
  {
    id: 9,
    title: 'Europe Street beat',
    description: 'www.instagram.com',
    image: 'https://picsum.photos/400/300',
    time: '10:00 - 06/05/2025',
  },
  {
    id: 10,
    title: 'Europe Street beat',
    description: 'www.instagram.com',
    image: 'https://picsum.photos/400/300',
    time: '10:00 - 06/05/2025',
  },
  {
    id: 11,
    title: 'Europe Street beat',
    description: 'www.instagram.com',
    image: 'https://picsum.photos/400/300',
    time: '10:00 - 06/05/2025',
  },
  {
    id: 12,
    title: 'Lịch nghỉ lễ 30/4 - 1/5',
    description: 'Lịch nghỉ lễ 30/4 - 1/5 năm 2025',
    image: 'https://picsum.photos/400/300',
    time: '10:00 - 06/05/2025',
  },
  {
    id: 13,
    title: 'Lịch nghỉ lễ 2/9',
    description: 'Lịch nghỉ lễ 2/9 năm 2025. Thay đổi giờ làm việc',
    image: 'https://picsum.photos/400/300',
    time: '10:00 - 06/05/2025',
  },
  {
    id: 14,
    title: 'Nhân sự mới',
    description: 'Chào đón nhân sự mới Nguyễn Văn A',
    image: 'https://picsum.photos/400/300',
    time: '10:00 - 06/05/2025',
  },
  {
    id: 15,
    title: 'Europe Street beat',
    description: 'www.instagram.com',
    image: 'https://picsum.photos/400/300',
    time: '10:00 - 06/05/2025',
  },
  {
    id: 16,
    title: 'Europe Street beat',
    description: 'www.instagram.com',
    image: 'https://picsum.photos/400/300',
    time: '10:00 - 06/05/2025',
  },
  {
    id: 17,
    title: 'Europe Street beat',
    description: 'www.instagram.com',
    image: 'https://picsum.photos/400/300',
    time: '10:00 - 06/05/2025',
  },
]
